https://wwwnc.cdc.gov/eid/article/1/1/95-0102_article
https://www.ncbi.nlm.nih.gov/pubmed/8021609
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4369385/

In [17]:
import pandas as pd
import matplotlib.pyplot as plt
from Bio import SeqIO
from Bio.Seq import Seq
from Bio.Alphabet import IUPAC

MN970003
Seq('TAAACACCTCATACCACTTATGTACAAAGGACTTCCTTGGAATGTAGTGCGTAT...TTG', SingleLetterAlphabet())
290
MN975268
Seq('AATGTCTATGCAGATTCATTTGTAATTAGAGGTGATGAAGTCAGACAAATCGCT...TTT', SingleLetterAlphabet())
107
MN975266
Seq('AATGTCTATGCAGATTCATTTGTAATTAGAGGTGATGAAGTCAGACAAATCGCT...TTT', SingleLetterAlphabet())
107
MN975263
Seq('TGAGTTATGAGGATCAAGATGCACTTTTCGCATATACAAAACGTAATGTCATCC...CTT', SingleLetterAlphabet())
287
MN938387
Seq('AATGTCTATGCAGATTCATTTGTAATTAGAGGTGATGAAGTCAGACAAATCGCT...TTT', SingleLetterAlphabet())
107
MN938390
Seq('AATGTCTATGCAGATTCATTTGTAATTAGAGGTGATGAAGTCAGACAAATCGCT...TTT', SingleLetterAlphabet())
107
MN938388
Seq('AATGTCTATGCAGATTCATTTGTAATTAGAGGTGATGAAGTCAGACAAATCGCT...TTT', SingleLetterAlphabet())
107
MN938389
Seq('AATGTCTATGCAGATTCATTTGTAATTAGAGGTGATGAAGTCAGACAAATCGCT...TTT', SingleLetterAlphabet())
107
MN975264
Seq('TGAGTTATGAGGATCAAGATGCACTTTTCGCATATACAAAACGTAATGTCATCC...CTT', SingleLetterAlphabet())
287
MN938385
Seq('TGAGTTATGAGGATCAAGATGCACTTTTCGCATATACAAAACGTAATGTCATCC...CTT', SingleLetterAlphabet())
287
MN938386
Seq('TGAGTTATGAGGATCAAGATGCACTTTTCGCATATACAAAACGTAATGTCATCC...CTT', SingleLetterAlphabet())
287
MN975267
Seq('AATGTCTATGCAGATTCATTTGTAATTAGAGGTGATGAAGTCAGACAAATCGCT...TTT', SingleLetterAlphabet())
107
MN970004
Seq('TAAACACCTCATACCACTTATGTACAAAGGACTTCCTTGGAATGTAGTGCGTAT...TTG', SingleLetterAlphabet())
290
MN975265
Seq('TGAGTTATGAGGATCAAGATGCACTTTTCGCATATACAAAACGTAATGTCATCC...CTT', SingleLetterAlphabet())
287
MN988669
Seq('TTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCTCTTGTA...AAA', SingleLetterAlphabet())
29881
MN988668
Seq('TTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCTCTTGTA...AAA', SingleLetterAlphabet())
29881
MN985325
Seq('ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCTCTTGT...AAA', SingleLetterAlphabet())
29882
MN938384
Seq('CAACCAACTTTCGATCTCTTGTAGATCTGTTCTCTAAACGAACTTTAAAATCTG...GAC', SingleLetterAlphabet())
29838
NC_045512
Seq('ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCTCTTGT...AAA', SingleLetterAlphabet())
29903
MN975262
Seq('ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCTCTTGT...AAA', SingleLetterAlphabet())
29891
MN908947
Seq('ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCTCTTGT...AAA', SingleLetterAlphabet())
29903
MN994467
Seq('ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCTCTTGT...AAA', SingleLetterAlphabet())
29882
MN994468
Seq('ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCTCTTGT...AAA', SingleLetterAlphabet())
29883
MN997409
Seq('ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCTCTTGT...AAA', SingleLetterAlphabet())
29882
MN988713
Seq('ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCTCTTGT...AAA', SingleLetterAlphabet())
29882

In [18]:
genome_list = pd.read_csv('PublishedGenomes.csv')
genome_list['Collection Date'] = pd.to_datetime(genome_list['Collection Date'])
genome_list.sort_values(by=['Collection Date'])

genome_list

   Accession Gene Region Collection Date         Locality
0   MN908947    complete      2019-12-01            China
1   MN970003        RdRP      2020-01-08         Thailand
2   MN970004        RdRP      2020-01-13         Thailand
3   MN938384    complete      2020-01-01  China: Shenzhen
4   MN938385        RdRP      2020-01-01  China: Shenzhen
5   MN938386        RdRP      2020-01-01  China: Shenzhen
6   MN938387           S      2020-01-01  China: Shenzhen
7   MN938388           S      2020-01-01  China: Shenzhen
8   MN938389           S      2020-01-01  China: Shenzhen
9   MN938390           S      2020-01-01  China: Shenzhen
10  MN975262    complete      2020-01-01            China
11  MN975263        RdRP      2020-01-01            China
12  MN975264        RdRP      2020-01-01            China
13  MN975265        RdRP      2020-01-01            China
14  MN975266           S      2020-01-01            China
15  MN975267           S      2020-01-01            China
16  MN975268           S      2020-01-01            China
17  MN985325    complete      2020-01-19          USA: WA
18  MN988713    complete      2020-01-21          USA: IL

In [31]:
S = SeqIO.parse('S.fasta', 'fasta')

for seq_record in S:
    #print(seq_record.id)
    print(seq_record)
    #print(repr(seq_record.seq))
    #print(len(seq_record))

ID: MN938387.1
Name: MN938387.1
Description: MN938387.1 Wuhan seafood market pneumonia virus isolate 2019-nCoV_HKU-SZ-001_2020 surface glycoprotein (S) gene, partial cds
Number of features: 0
Seq('AATGTCTATGCAGATTCATTTGTAATTAGAGGTGATGAAGTCAGACAAATCGCT...TTT', SingleLetterAlphabet())
ID: MN938388.1
Name: MN938388.1
Description: MN938388.1 Wuhan seafood market pneumonia virus isolate 2019-nCoV_HKU-SZ-002b_2020 surface glycoprotein (S) gene, partial cds
Number of features: 0
Seq('AATGTCTATGCAGATTCATTTGTAATTAGAGGTGATGAAGTCAGACAAATCGCT...TTT', SingleLetterAlphabet())
ID: MN938389.1
Name: MN938389.1
Description: MN938389.1 Wuhan seafood market pneumonia virus isolate 2019-nCoV_HKU-SZ-004_2020 surface glycoprotein (S) gene, partial cds
Number of features: 0
Seq('AATGTCTATGCAGATTCATTTGTAATTAGAGGTGATGAAGTCAGACAAATCGCT...TTT', SingleLetterAlphabet())
ID: MN938390.1
Name: MN938390.1
Description: MN938390.1 Wuhan seafood market pneumonia virus isolate 2019-nCoV_HKU-SZ-005_2020 surface glycoprotein (S) gene, partial cds
Number of features: 0
Seq('AATGTCTATGCAGATTCATTTGTAATTAGAGGTGATGAAGTCAGACAAATCGCT...TTT', SingleLetterAlphabet())
ID: MN975266.1
Name: MN975266.1
Description: MN975266.1 Wuhan seafood market pneumonia virus isolate 2019-nCoV_HKU-SZ-007a_2020 surface glycoprotein (S) gene, partial cds
Number of features: 0
Seq('AATGTCTATGCAGATTCATTTGTAATTAGAGGTGATGAAGTCAGACAAATCGCT...TTT', SingleLetterAlphabet())
ID: MN975267.1
Name: MN975267.1
Description: MN975267.1 Wuhan seafood market pneumonia virus isolate 2019-nCoV_HKU-SZ-007b_2020 surface glycoprotein (S) gene, partial cds
Number of features: 0
Seq('AATGTCTATGCAGATTCATTTGTAATTAGAGGTGATGAAGTCAGACAAATCGCT...TTT', SingleLetterAlphabet())
ID: MN975268.1
Name: MN975268.1
Description: MN975268.1 Wuhan seafood market pneumonia virus isolate 2019-nCoV_HKU-SZ-007c_2020 surface glycoprotein (S) gene, partial cds
Number of features: 0
Seq('AATGTCTATGCAGATTCATTTGTAATTAGAGGTGATGAAGTCAGACAAATCGCT...TTT', SingleLetterAlphabet())